name: Deploy para VM Local

# Evento que dispara o workflow
on:
  push:
    branches:
      - main   # substitua se o seu branch tiver outro nome

jobs:
  deploy:
    runs-on: self-hosted  # roda no seu runner Vagrant!

    steps:
    # 1️⃣ Clona/atualiza o código do repositório
    - name: Checkout do código
      uses: actions/checkout@v3

    # 2️⃣ Atualiza os arquivos do site
    - name: Atualizar site
      run: |
        cd /var/www/html
        sudo git pull origin main
        echo "Arquivos atualizados em $(date)"

    # 3️⃣ Reinicia o Nginx para aplicar mudanças
    - name: Reiniciar Nginx
      run: |
        sudo systemctl restart nginx
        echo "Nginx reiniciado com sucesso em $(date)"
